version: "3.1"

services:

    postgresqldb:
      image: "postgres:latest"
      restart: "always"
      environment:
        POSTGRES_PASSWORD: "passw0rd"
      network:
        - dbnetwork

    pgadmin:
      image: "dpage/pgadmin4"
      ports:
        - 80:80
      network:
        - dbnetwork

    